import TeamCard from "./TeamCard";

function Team() {

    return (
        <div id="Team" className="flex flex-col justify-evenly items-center">
            <span className="text-4xl font-semibold uppercase py-10">our team</span>
            <div className="grid grid-cols-1 md:grid-cols-2 space-x-2">
                <TeamCard imgSrc='https://fwm-media.s3.us-west-2.amazonaws.com/karlie.jpeg' first="Karlie" last="Haskins" job="Business Manger | Sales" description="Karlie received a Bachelor's degree from Penn State University, and after four years of constantly talking about Idaho, she moved home to contribute to the growth of a community she feels connected to. She worked as a cross-cultural dialogue facilitator for three years, and learned how to guide a conversation so people may think together about an idea. Through this experience, she recognized how a person’s community often influences their experience. This inspired her to pursue marketing, so she can work directly with business professionals to determine how they can effectively connect with their customers and communities." />
                <TeamCard imgSrc='https://fwm-media.s3.us-west-2.amazonaws.com/nick.jpeg' first="Nick" last="Giegerich" job="Software Engineer" description="Nick is passionate about Computer Science, and enjoys working on a wide variety of projects-- from simple one page websites, to enterprise level data applications. He has worked in Southeast Asia and Northeast Canada, and is no stranger to working with diverse teams and leveraging a wide variety of technologies." />
                <TeamCard imgSrc='https://fwm-media.s3.us-west-2.amazonaws.com/porter.jpeg' first="Porter" last="Wilcox" job="Software Engineer" description="Porter realized that a majority of his free time was spent playing chess and sudoku, so he decided to align his career appropriately. He enrolled in a local coding boot camp school, and was quickly invited to teach the classes he had just attended. In the Fall of 2019, he felt a similar sense of curiosity that carried him through his undergraduate experience studying philosophy; so he refined his web development skills and pursued freelance work while embarking on a 7 month journey through the PNW and South America. Porter has since moved back to Idaho, but he continues to build websites, and iOS and Android applications." />
                <TeamCard imgSrc='https://fwm-media.s3.us-west-2.amazonaws.com/marcelino.jpg' first="Marcelino" last="Arenz" job="Graphic Designer | UX" description="Marcelino is a multidisciplinary creative with a special interest in storytelling and experiential design. A professional river guide during the summer, and with a BFA in graphic design from the University of Idaho under his belt, he understands the impact and authenticity of experience. Trained in the vernacular of the Adobe Suite, and mentored by industry professionals, he is skilled in combining type, photos, and graphics into a medley that creates a captivating visual experience." />
                <TeamCard imgSrc='https://fwm-media.s3.us-west-2.amazonaws.com/sean.jpeg' first="Sean" last="Muldoon" job="Owner | CEO" description="Sean is the Founder and Lead Content Developer at Forever Wild Media. He received a degree in Biotechnology and spent four years in the agriculture industry--where he developed drone technology to monitor and track plant health. As his knowledge and understanding for imaging and storytelling grew, he decided to change course and dedicate all of his time and energy toward his passion for videography. His focus with Forever Wild Media is to use storytelling to bring his client’s vision to life." />
            </div>
        </div>
    )
}

export default Team;